contact_links:
  - name: Bug Report
    about: Create a report of the issue you've encountered.
    url: https://github.com/costimize/app/issues/new?projects=costimize%2Fapp%2F1&assignees=costimize&labels=bug&template=bug&title=BUG%3A
  - name: Feature request
    about: Suggest an idea for this project.
    url: https://github.com/costimize/app/issues/new?projects=costimize%2Fapp%2F1&assignees=costimize&labels=enhancement&template=feature&title=FEATURE%3A
